ALTER TABLE work_shifts 
ADD COLUMN IF NOT EXISTS enforce_lateness BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS enforce_lunch_limit BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS enforce_geofence BOOLEAN NOT NULL DEFAULT true;
